//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserWPFApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UserWPFApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View field.
        /// </summary>
        public static string btnOpenField {
            get {
                return ResourceManager.GetString("btnOpenField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View statistics.
        /// </summary>
        public static string btnTeam {
            get {
                return ResourceManager.GetString("btnTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Starting Positions.
        /// </summary>
        public static string fieldTitle {
            get {
                return ResourceManager.GetString("fieldTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Championship.
        /// </summary>
        public static string lblChampionship {
            get {
                return ResourceManager.GetString("lblChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa Cod.
        /// </summary>
        public static string lblCode {
            get {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeats.
        /// </summary>
        public static string lblDefeat {
            get {
                return ResourceManager.GetString("lblDefeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal Difference.
        /// </summary>
        public static string lblDifference {
            get {
                return ResourceManager.GetString("lblDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws.
        /// </summary>
        public static string lblDraw {
            get {
                return ResourceManager.GetString("lblDraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scor.
        /// </summary>
        public static string lblInfo {
            get {
                return ResourceManager.GetString("lblInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Language.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Goals.
        /// </summary>
        public static string lblReceived {
            get {
                return ResourceManager.GetString("lblReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Resolution.
        /// </summary>
        public static string lblResolution {
            get {
                return ResourceManager.GetString("lblResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scored Goals.
        /// </summary>
        public static string lblScored {
            get {
                return ResourceManager.GetString("lblScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins.
        /// </summary>
        public static string lblWins {
            get {
                return ResourceManager.GetString("lblWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Of Representations.
        /// </summary>
        public static string mainTitle {
            get {
                return ResourceManager.GetString("mainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your preferences.
        /// </summary>
        public static string preferencesTitle {
            get {
                return ResourceManager.GetString("preferencesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string tbGoals {
            get {
                return ResourceManager.GetString("tbGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string tbName {
            get {
                return ResourceManager.GetString("tbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string tbNumber {
            get {
                return ResourceManager.GetString("tbNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string tbPosition {
            get {
                return ResourceManager.GetString("tbPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string tbSurname {
            get {
                return ResourceManager.GetString("tbSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards.
        /// </summary>
        public static string tbYellowCards {
            get {
                return ResourceManager.GetString("tbYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of the Team.
        /// </summary>
        public static string teamDetailsTitle {
            get {
                return ResourceManager.GetString("teamDetailsTitle", resourceCulture);
            }
        }
    }
}
